---
title: "GEV Univariate/Bivariate - EDA"
author: "Mongi Nouira"
output: github_document
---

```{r, include=FALSE}
library(htmltools)

knitr::knit_hooks$set(imgcenter = function(before, options, envir){
  if (before) {
    HTML("<p align='center'>")
  } else {
    HTML("</p>")
  }
})

knitr::opts_chunk$set(
  echo=FALSE, cache=TRUE, imgcenter=TRUE, 
  fig.align="center", dpi=150, fig.width=7
)

library("ismev")
library("evd")

# Color Map
c1 = "#636EFA"
c2 = "#EF553B"
c3 = "#00CC96"
```

```{r}
df = read.csv("~/Documents/GitHub/PDM_2022/data/data1.csv")

ll = -100*sapply(df[seq(2,12)], function(x) log(x[-1])-log(x[-length(df$Date)]))
#ll = apply(ll, c(1,2), function(x) max(x,0))
ll = data.frame(ll)
ll$Date = df$Date[-1]
```

```{r}
cml = ll[ll[,6]>2&ll[,7]>2,c(6,7)]

pp = "pickands"
cc = "cfg"

par(pty="s", oma=c(0,0,2,0))

abvnonpar(data = cml, epmar = TRUE, method = pp, plot = TRUE, lty = 1, col=c1)
abvnonpar(data = cml, epmar = TRUE, method = pp, add = TRUE, madj = 1, lty = 2)
abvnonpar(data = cml, epmar = TRUE, method = pp, add = TRUE, madj = 2, lty = 3)
abvnonpar(data = cml, epmar = TRUE, method = cc, add = TRUE, lty = 4)

legend(
  "bottomright", 
  legend=c("Pickands","Deheuvels","Hall-Tajvidi","Caperaa-Fougeres-Genest"), 
  col=c(c1,'black','black','black'), lty=1:4, cex=0.6
)

par(oma=c(0,0,0,0))
title(main="Non-Parametric Estimation Of Dependence Function")
```

```{r, echo=FALSE}
sup_u = ll$S.P.Technology>2 & ll$S.P.Energy>2
fitbv <- fbvevd(ll[sup_u,c(6,7)], model="log", std.err=FALSE)
fitbv
```

```{r, fig.asp=1}
par(mfrow=c(2,2), pty="s")
plot(fitbv, mar=1, which=c(3,4))
plot(fitbv, mar=2, which=c(3,4))
```

```{r, fig.asp=1}
par(mfrow=c(2,2), pty="s")
plot(fitbv, which=c(3,4))
plot(fitbv, which=c(5,6))
```