---
title: "Test Package texmex"
author: "Mongi Nouira"
output: github_document
---

```{r, include=FALSE}
library(htmltools)

knitr::knit_hooks$set(imgcenter = function(before, options, envir){
  if (before) {
    HTML("<p align='center'>")
  } else {
    HTML("</p>")
  }
})

rmd_filename = stringr::str_remove(knitr::current_input(), "\\.Rmd")
knitr::opts_chunk$set(
  fig.path = stringr::str_c(file.path("cache", rmd_filename), "/")
)

knitr::opts_chunk$set(
  echo=FALSE, cache=TRUE, imgcenter=TRUE,
  fig.align="center", dpi=150, fig.width=8, fig.height=6
)

# Color Map
c1 = "#636EFA"
c2 = "#EF553B"
c3 = "#00CC96"

library("texmex")
library("tictoc")

options(digits=2)
set.seed(20130619)
```


```{r}
df = read.csv("~/Documents/GitHub/PDM_2022/data/data1.csv")

# Data
ll = -100*sapply(df[seq(2,ncol(df))], function(x) log(x[-1])-log(x[-length(df$Date)]))
ll = apply(ll, c(1,2), function(x) max(x,0))
ll = data.frame(ll)

# Sectors
sectors = sapply(colnames(ll)[1:12], function(x) substring(x,5))
sectors = as.vector(sectors)
colnames(ll) = sectors

# Filter
#ll = ll[!(ll$Market==0 & apply(ll[,2:12]!=0,1,any)),]
```

## Marginal GPD Model Fit
### Summary

```{r}
marg <- migpd(ll, mth=2, penalty="none", family=gpd)
summary(marg)$co
```

### Diagnostic
Done in EDA section.

## Dependence Model Fit
### Summary

```{r}
cmod <- mexDependence(marg, which="Market", dqu=0.9, margins="laplace", constrain=TRUE)
cmod$dependence
```

### Diagnostic

```{r, fig.height=3}
par(pty="s", mfcol=c(1,3))
plot(cmod)
```

### Dependence Model Threshold Selection

```{r}
start = matrix(
  c(0.5,0.2, 
    0.1,0.2, 
    0.5,0.2,
    0.6,0.2,
    0.6,0.2,
    0.6,0.2,
    0.4,0.2,
    0.6,0.2,
    0.5,0.2,
    0.5,0.2,
    0.5,0.2), 
  nrow=2, ncol=11, byrow=F
)

last = coef(cmod$dependence)[1:2,]
```


```{r}
tic("mexRangeFit run time")
mrf <- mexRangeFit(marg, which="Market", margins="laplace", constrain=TRUE, start=start, 
                   quantiles=c(0.8,0.85,0.9,0.95), trace=11)
toc()
```


```{r}
par(mfrow=c(3,2))
plot(mrf)
```

### Dependence Model 2

```{r}
cmod <- mexDependence(marg, which="Market", dqu=0.95, margins="laplace", start=start,
                      PlotLikDo=T, PlotLikRange=list(a=c(0,1),b=c(-1,1)))
```


```{r}
cmod$dependence
```


```{r, fig.height=3}
par(pty="s", mfcol=c(1,3))
plot(cmod)
```

```{r}
params = cmod$dependence$coefficients[1:2,]

par(pty="s")
plot(t(params), xlim=c(0.5,1.4), ylim=c(-0.1,0.22), col=c1)
text(t(params), colnames(params), pos=4, offset=0.5, cex=0.5)
grid()
```


```{r}
pred = predict(cmod, pqu=0.9, nsim=nrow(ll))
summary(pred)
```


```{r}
par(pty="s", mfrow=c(3,4), mar=c(2,4,1,1))
plot(pred)
```





